url: http://1.zackwo.com

title: 金点原子保险柜

keywords: 

description: 

address: 浙江省宁波市北仑区白峰镇阳东村钟家湾88-4

tel: 0574-86728236

phone: 13656781331

service-tel: 95116

email: xxxxx@xxx.com

qq: 123456789

weixin: 13656781331

exclude:
  - README.md
  - style.css
