url: https://www.jdyzsafe.com

title: 金点原子保险柜

keywords: 保险柜

description: 宁波弗雷迪安防科技有限公司为金点原子旗下保险柜事业部专业负责金点原子保险柜的生产与销售工作，主要系列有金猴系列、金鸡系列、金虎系列等。

address: 浙江省宁波市北仑区白峰镇阳东村钟家湾88-4

tel: 0574-86728236

phone: 13656781331

service-tel: 95116

email: safeone@qq.com

qq: 137991839

weixin: 13656781331

exclude:
  - README.md
  - style.css
